services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - websocket

  websocket:
    build: ./websocket
    env_file:
      - ./websocket/.env
    ports:
      - "5000:5000"

  db:
    image: postgres:16-alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
