services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - db
    env_file: []
    environment:
      DB_URL: "{BACKEND_DB_URL}"
      JWT_SECRET: "{BACKEND_JWT_SECRET}"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - websocket
    env_file: []
    environment:
      NEXT_PUBLIC_API_URL: "{FRONTEND_API_URL}"

  websocket:
    build: ./websocket
    ports:
      - "5000:5000"
      - "5001:5001"
    env_file: []
    environment:
      WS_PORT: "${WS_PORT:-5000}"
      WS_HEALTH_PORT: "{WS_HEALTH_PORT:-5001}"

  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: []
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: axiom_db

volumes:
  pgdata:
